apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: storage-api
  name: storage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: storage-api
    spec:
      containers:
        - image: storageapi:latest
          name: storage-api
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
